# Generated by Django 5.1.1 on 2025-05-04 05:21

import django.db.models.deletion
import quiz.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MultiChoiceQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('a_text', models.CharField(max_length=255)),
                ('a_correct', models.BooleanField(default=False)),
                ('b_text', models.CharField(max_length=255)),
                ('b_correct', models.BooleanField(default=False)),
                ('c_text', models.CharField(max_length=255)),
                ('c_correct', models.BooleanField(default=False)),
                ('d_text', models.CharField(max_length=255)),
                ('d_correct', models.BooleanField(default=False)),
                ('randomize_order', models.BooleanField(default=True)),
                ('question_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.questiongroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=quiz.models.quiz_slug, editable=False)),
                ('title', models.CharField(default='My Quiz', max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='questiongroup',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz'),
        ),
        migrations.CreateModel(
            name='TrueFalseQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.BooleanField()),
                ('question_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.questiongroup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
