# Generated by Django 5.1.1 on 2025-05-09 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MultiChoiceQuestion',
            new_name='Question',
        ),
        migrations.AlterModelOptions(
            name='questiongroup',
            options={'ordering': ('ordering',)},
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(default='New Quiz', max_length=255),
        ),
        migrations.DeleteModel(
            name='TrueFalseQuestion',
        ),
    ]
