# Generated by Django 5.1.1 on 2025-02-27 03:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(default='')),
                ('title', models.CharField(default='', max_length=255)),
                ('content', models.TextField(default='')),
            ],
        ),
    ]
