# Generated by Django 5.2.1 on 2025-05-22 00:09

import bot.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatPoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broadcaster_user_id', models.CharField(max_length=255)),
                ('in_progress', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('choices', models.JSONField()),
                ('votes', models.JSONField()),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(default=bot.models.default_ends_at)),
            ],
        ),
    ]
