# Generated by Django 4.2.11 on 2024-08-30 16:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LastFMGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('username', models.CharField(max_length=255)),
                ('period', models.CharField(max_length=255)),
                ('size', models.IntegerField(default=9)),
                ('results', models.JSONField()),
            ],
        ),
    ]
