# Generated by Django 4.2.11 on 2024-08-30 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lastfm', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lastfmgrid',
            unique_together={('username', 'period', 'size')},
        ),
    ]
