# Generated by Django 5.2.5 on 2025-08-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lastfm', '0003_alter_lastfmgrid_results'),
    ]

    operations = [
       migrations.AddField(
            model_name='lastfmgrid',
            name='height',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='lastfmgrid',
            name='width',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterUniqueTogether(
            name='lastfmgrid',
            unique_together={('username', 'period', 'width', 'height')},
        ),
    ]
