# Generated by Django 5.2.5 on 2025-08-29 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lastfm', '0004_alter_lastfmgrid_unique_together_lastfmgrid_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lastfmgrid',
            name='size',
        ),
    ]
