# Generated by Django 4.2.9 on 2024-02-22 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import overlay.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaborativeOverlay',
            fields=[
                ('id', models.CharField(default=overlay.models.id_gen, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(default='My Overlay', max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('width', models.IntegerField(default=1920)),
                ('height', models.IntegerField(default=1080)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimerItem',
            fields=[
                ('id', models.CharField(default=overlay.models.id_gen, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(default='My Item', max_length=256)),
                ('x', models.IntegerField(default=-100)),
                ('y', models.IntegerField(default=-100)),
                ('z', models.IntegerField(default=50)),
                ('width', models.IntegerField(default=50)),
                ('height', models.IntegerField(default=50)),
                ('rotation', models.FloatField(default=0)),
                ('visible', models.BooleanField(default=True)),
                ('font_size', models.IntegerField(default=12)),
                ('color', models.CharField(default='#FFFFFF', max_length=64)),
                ('outline', models.CharField(default='#000000', max_length=64)),
                ('outline_enabled', models.BooleanField(default=False)),
                ('item_type', models.CharField(default='TimerItem', editable=False, max_length=32)),
                ('timer_start', models.BigIntegerField(default=1708579445)),
                ('overlay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overlay.collaborativeoverlay')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TextItem',
            fields=[
                ('id', models.CharField(default=overlay.models.id_gen, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(default='My Item', max_length=256)),
                ('x', models.IntegerField(default=-100)),
                ('y', models.IntegerField(default=-100)),
                ('z', models.IntegerField(default=50)),
                ('width', models.IntegerField(default=50)),
                ('height', models.IntegerField(default=50)),
                ('rotation', models.FloatField(default=0)),
                ('visible', models.BooleanField(default=True)),
                ('font_size', models.IntegerField(default=12)),
                ('color', models.CharField(default='#FFFFFF', max_length=64)),
                ('outline', models.CharField(default='#000000', max_length=64)),
                ('outline_enabled', models.BooleanField(default=False)),
                ('item_type', models.CharField(default='TextItem', editable=False, max_length=32)),
                ('text', models.TextField(default='Example text.')),
                ('overlay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overlay.collaborativeoverlay')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageItem',
            fields=[
                ('id', models.CharField(default=overlay.models.id_gen, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(default='My Item', max_length=256)),
                ('x', models.IntegerField(default=-100)),
                ('y', models.IntegerField(default=-100)),
                ('z', models.IntegerField(default=50)),
                ('width', models.IntegerField(default=50)),
                ('height', models.IntegerField(default=50)),
                ('rotation', models.FloatField(default=0)),
                ('visible', models.BooleanField(default=True)),
                ('item_type', models.CharField(default='ImageItem', editable=False, max_length=32)),
                ('url', models.TextField(default='')),
                ('overlay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overlay.collaborativeoverlay')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.CharField(default=overlay.models.id_gen, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=256)),
                ('twitch_id', models.CharField(max_length=256)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CounterItem',
            fields=[
                ('id', models.CharField(default=overlay.models.id_gen, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(default='My Item', max_length=256)),
                ('x', models.IntegerField(default=-100)),
                ('y', models.IntegerField(default=-100)),
                ('z', models.IntegerField(default=50)),
                ('width', models.IntegerField(default=50)),
                ('height', models.IntegerField(default=50)),
                ('rotation', models.FloatField(default=0)),
                ('visible', models.BooleanField(default=True)),
                ('font_size', models.IntegerField(default=12)),
                ('color', models.CharField(default='#FFFFFF', max_length=64)),
                ('outline', models.CharField(default='#000000', max_length=64)),
                ('outline_enabled', models.BooleanField(default=False)),
                ('item_type', models.CharField(default='CounterItem', editable=False, max_length=32)),
                ('counter_format', models.TextField(default='Count: {0}')),
                ('count', models.IntegerField(default=0)),
                ('overlay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overlay.collaborativeoverlay')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
