# Generated by Django 4.2.9 on 2024-02-24 06:52

from django.db import migrations, models
import overlay.models


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stopwatchitem',
            name='pause_time',
            field=models.BigIntegerField(default=overlay.models.current_time_seconds),
        ),
        migrations.AlterField(
            model_name='stopwatchitem',
            name='timer_start',
            field=models.BigIntegerField(default=overlay.models.current_time_seconds),
        ),
    ]
