# Generated by Django 4.2.9 on 2024-02-13 04:56

from django.db import migrations, models
import overlay.models


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborativeoverlay',
            name='id',
            field=models.CharField(default=overlay.models.id_gen, editable=False, max_length=16, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='editor',
            name='id',
            field=models.CharField(default=overlay.models.id_gen, editable=False, max_length=16, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='imageitem',
            name='id',
            field=models.CharField(default=overlay.models.id_gen, editable=False, max_length=16, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='textitem',
            name='id',
            field=models.CharField(default=overlay.models.id_gen, editable=False, max_length=16, primary_key=True, serialize=False),
        ),
    ]
