# Generated by Django 4.2.9 on 2024-02-22 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0002_alter_timeritem_timer_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeritem',
            name='timer_start',
            field=models.BigIntegerField(default=1708579697),
        ),
    ]
