# Generated by Django 4.2.9 on 2024-02-25 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0002_alter_stopwatchitem_pause_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counteritem',
            name='font_size',
            field=models.IntegerField(default=32),
        ),
        migrations.AlterField(
            model_name='counteritem',
            name='height',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='counteritem',
            name='width',
            field=models.IntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='counteritem',
            name='x',
            field=models.IntegerField(default=-300),
        ),
        migrations.AlterField(
            model_name='imageitem',
            name='height',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='imageitem',
            name='width',
            field=models.IntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='imageitem',
            name='x',
            field=models.IntegerField(default=-300),
        ),
        migrations.AlterField(
            model_name='stopwatchitem',
            name='font_size',
            field=models.IntegerField(default=32),
        ),
        migrations.AlterField(
            model_name='stopwatchitem',
            name='height',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='stopwatchitem',
            name='width',
            field=models.IntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='stopwatchitem',
            name='x',
            field=models.IntegerField(default=-300),
        ),
        migrations.AlterField(
            model_name='textitem',
            name='font_size',
            field=models.IntegerField(default=32),
        ),
        migrations.AlterField(
            model_name='textitem',
            name='height',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='textitem',
            name='width',
            field=models.IntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='textitem',
            name='x',
            field=models.IntegerField(default=-300),
        ),
    ]
