# Generated by Django 4.2.9 on 2024-02-14 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0002_alter_collaborativeoverlay_id_alter_editor_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageitem',
            name='item_type',
            field=models.CharField(default='ImageItem', editable=False, max_length=32),
        ),
        migrations.AddField(
            model_name='textitem',
            name='item_type',
            field=models.CharField(default='TextItem', editable=False, max_length=32),
        ),
        migrations.AlterField(
            model_name='imageitem',
            name='name',
            field=models.CharField(default='My Item', max_length=256),
        ),
        migrations.AlterField(
            model_name='textitem',
            name='name',
            field=models.CharField(default='My Item', max_length=256),
        ),
    ]
