# Generated by Django 4.2.9 on 2024-02-16 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0003_imageitem_item_type_textitem_item_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='textitem',
            name='font_size',
            field=models.IntegerField(default=12),
        ),
    ]
