# Generated by Django 4.2.9 on 2024-02-25 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0003_alter_counteritem_font_size_alter_counteritem_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='counteritem',
            name='font',
            field=models.CharField(default='Bungee Spice', max_length=128),
        ),
        migrations.AddField(
            model_name='stopwatchitem',
            name='font',
            field=models.CharField(default='Bungee Spice', max_length=128),
        ),
        migrations.AddField(
            model_name='textitem',
            name='font',
            field=models.CharField(default='Bungee Spice', max_length=128),
        ),
    ]
