# Generated by Django 4.2.9 on 2024-02-22 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0003_alter_timeritem_timer_start'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimerItem',
        ),
    ]
