# Generated by Django 4.2.9 on 2024-03-12 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0004_counteritem_font_stopwatchitem_font_textitem_font'),
    ]

    operations = [
        migrations.AddField(
            model_name='counteritem',
            name='minimized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imageitem',
            name='minimized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stopwatchitem',
            name='minimized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='textitem',
            name='minimized',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='counteritem',
            name='font',
            field=models.CharField(default='Roboto Mono', max_length=128),
        ),
        migrations.AlterField(
            model_name='stopwatchitem',
            name='font',
            field=models.CharField(default='Roboto Mono', max_length=128),
        ),
        migrations.AlterField(
            model_name='textitem',
            name='font',
            field=models.CharField(default='Roboto Mono', max_length=128),
        ),
    ]
