# Generated by Django 4.2.9 on 2024-02-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0004_textitem_font_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageitem',
            name='z',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='textitem',
            name='z',
            field=models.IntegerField(default=0),
        ),
    ]
