# Generated by Django 4.2.9 on 2024-02-17 07:27

from django.db import migrations, models
import django.db.models.deletion
import overlay.models


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0005_imageitem_z_textitem_z'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageitem',
            name='z',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='textitem',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=64),
        ),
        migrations.AlterField(
            model_name='textitem',
            name='outline',
            field=models.CharField(default='#000000', max_length=64),
        ),
        migrations.AlterField(
            model_name='textitem',
            name='z',
            field=models.IntegerField(default=50),
        ),
        migrations.CreateModel(
            name='TimerItem',
            fields=[
                ('id', models.CharField(default=overlay.models.id_gen, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(default='My Item', max_length=256)),
                ('x', models.IntegerField(default=-100)),
                ('y', models.IntegerField(default=-100)),
                ('z', models.IntegerField(default=50)),
                ('width', models.IntegerField(default=50)),
                ('height', models.IntegerField(default=50)),
                ('rotation', models.FloatField(default=0)),
                ('visible', models.BooleanField(default=True)),
                ('font_size', models.IntegerField(default=12)),
                ('color', models.CharField(default='#FFFFFF', max_length=64)),
                ('outline', models.CharField(default='#000000', max_length=64)),
                ('outline_enabled', models.BooleanField(default=False)),
                ('item_type', models.CharField(default='TimerItem', editable=False, max_length=32)),
                ('timer_start', models.DateTimeField(verbose_name='timer start')),
                ('overlay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overlay.collaborativeoverlay')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
