# Generated by Django 4.2.9 on 2024-04-06 22:37

from django.db import migrations, models
import overlay.models


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0005_counteritem_minimized_imageitem_minimized_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=overlay.models.image_directory_path),
        ),
        migrations.AlterField(
            model_name='imageitem',
            name='url',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
