# Generated by Django 4.2.9 on 2024-02-22 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0005_timeritem'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeritem',
            name='timer_format',
            field=models.TextField(default='{0}'),
        ),
        migrations.AlterField(
            model_name='timeritem',
            name='timer_start',
            field=models.BigIntegerField(default=1708580752),
        ),
    ]
