# Generated by Django 4.2.9 on 2024-02-17 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0006_alter_imageitem_z_alter_textitem_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageitem',
            name='url',
            field=models.TextField(default=''),
        ),
    ]
