# Generated by Django 4.2.9 on 2024-04-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0006_imageitem_image_alter_imageitem_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='counteritem',
            name='text_alignment',
            field=models.CharField(default='left', max_length=128),
        ),
        migrations.AddField(
            model_name='stopwatchitem',
            name='text_alignment',
            field=models.CharField(default='left', max_length=128),
        ),
        migrations.AddField(
            model_name='textitem',
            name='text_alignment',
            field=models.CharField(default='left', max_length=128),
        ),
        migrations.AlterField(
            model_name='imageitem',
            name='url',
            field=models.URLField(blank=True, default='', null=True, verbose_name='URL'),
        ),
    ]
