# Generated by Django 4.2.9 on 2024-04-08 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0007_counteritem_text_alignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='counteritem',
            name='font_weight',
            field=models.CharField(default='normal', max_length=128),
        ),
        migrations.AddField(
            model_name='stopwatchitem',
            name='font_weight',
            field=models.CharField(default='normal', max_length=128),
        ),
        migrations.AddField(
            model_name='textitem',
            name='font_weight',
            field=models.CharField(default='normal', max_length=128),
        ),
    ]
