# Generated by Django 4.2.9 on 2024-02-19 23:53

from django.db import migrations, models
import django.db.models.deletion
import overlay.models


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0007_alter_imageitem_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterItem',
            fields=[
                ('id', models.CharField(default=overlay.models.id_gen, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(default='My Item', max_length=256)),
                ('x', models.IntegerField(default=-100)),
                ('y', models.IntegerField(default=-100)),
                ('z', models.IntegerField(default=50)),
                ('width', models.IntegerField(default=50)),
                ('height', models.IntegerField(default=50)),
                ('rotation', models.FloatField(default=0)),
                ('visible', models.BooleanField(default=True)),
                ('font_size', models.IntegerField(default=12)),
                ('color', models.CharField(default='#FFFFFF', max_length=64)),
                ('outline', models.CharField(default='#000000', max_length=64)),
                ('outline_enabled', models.BooleanField(default=False)),
                ('item_type', models.CharField(default='CounterItem', editable=False, max_length=32)),
                ('counter_format', models.TextField(default='Count: {0}')),
                ('count', models.IntegerField(default=0)),
                ('overlay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overlay.collaborativeoverlay')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
