# Generated by Django 4.2.9 on 2024-02-23 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0007_stopwatchitem_delete_timeritem'),
    ]

    operations = [
        migrations.AddField(
            model_name='stopwatchitem',
            name='pause_time',
            field=models.BigIntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='stopwatchitem',
            name='paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stopwatchitem',
            name='timer_start',
            field=models.BigIntegerField(default=1708672794),
        ),
    ]
