# Generated by Django 4.2.9 on 2024-02-24 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0008_stopwatchitem_pause_time_stopwatchitem_paused_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counteritem',
            old_name='outline',
            new_name='background',
        ),
        migrations.RenameField(
            model_name='counteritem',
            old_name='outline_enabled',
            new_name='background_enabled',
        ),
        migrations.RenameField(
            model_name='stopwatchitem',
            old_name='outline',
            new_name='background',
        ),
        migrations.RenameField(
            model_name='stopwatchitem',
            old_name='outline_enabled',
            new_name='background_enabled',
        ),
        migrations.RenameField(
            model_name='textitem',
            old_name='outline',
            new_name='background',
        ),
        migrations.RenameField(
            model_name='textitem',
            old_name='outline_enabled',
            new_name='background_enabled',
        ),
        migrations.AlterField(
            model_name='stopwatchitem',
            name='pause_time',
            field=models.BigIntegerField(default=1708754450),
        ),
        migrations.AlterField(
            model_name='stopwatchitem',
            name='timer_start',
            field=models.BigIntegerField(default=1708754450),
        ),
    ]
