# Generated by Django 4.2.9 on 2024-04-08 22:58

from django.db import migrations, models
import django.db.models.deletion
import overlay.models


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0008_counteritem_font_weight_stopwatchitem_font_weight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbedItem',
            fields=[
                ('id', models.CharField(default=overlay.models.id_gen, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(default='My Item', max_length=256)),
                ('x', models.IntegerField(default=-300)),
                ('y', models.IntegerField(default=-100)),
                ('z', models.IntegerField(default=50)),
                ('width', models.IntegerField(default=300)),
                ('height', models.IntegerField(default=100)),
                ('rotation', models.FloatField(default=0)),
                ('visible', models.BooleanField(default=True)),
                ('minimized', models.BooleanField(default=False)),
                ('item_type', models.CharField(default='EmbedItem', editable=False, max_length=32)),
                ('embed_url', models.URLField(blank=True, default='', verbose_name='Embed URL')),
                ('overlay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overlay.collaborativeoverlay')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
