# Generated by Django 4.2.11 on 2024-04-20 19:38

from django.db import migrations, models
import django.db.models.deletion
import overlay.models


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0009_embeditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborativeoverlay',
            name='allow_audio',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='YouTubeEmbedItem',
            fields=[
                ('id', models.CharField(default=overlay.models.id_gen, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(default='My Item', max_length=256)),
                ('x', models.IntegerField(default=-300)),
                ('y', models.IntegerField(default=-100)),
                ('z', models.IntegerField(default=50)),
                ('width', models.IntegerField(default=300)),
                ('height', models.IntegerField(default=100)),
                ('rotation', models.FloatField(default=0)),
                ('visible', models.BooleanField(default=True)),
                ('minimized', models.BooleanField(default=False)),
                ('item_type', models.CharField(default='YoutubeEmbedItem', editable=False, max_length=32)),
                ('video_id', models.CharField(blank=True, default='', max_length=256, verbose_name='YouTube Video ID')),
                ('paused', models.BooleanField()),
                ('muted', models.BooleanField()),
                ('overlay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overlay.collaborativeoverlay')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TwitchStreamEmbedItem',
            fields=[
                ('id', models.CharField(default=overlay.models.id_gen, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(default='My Item', max_length=256)),
                ('x', models.IntegerField(default=-300)),
                ('y', models.IntegerField(default=-100)),
                ('z', models.IntegerField(default=50)),
                ('width', models.IntegerField(default=300)),
                ('height', models.IntegerField(default=100)),
                ('rotation', models.FloatField(default=0)),
                ('visible', models.BooleanField(default=True)),
                ('minimized', models.BooleanField(default=False)),
                ('item_type', models.CharField(default='TwitchEmbedItem', editable=False, max_length=32)),
                ('username', models.CharField(blank=True, default='', max_length=256, verbose_name='Twitch Channel Name')),
                ('paused', models.BooleanField()),
                ('muted', models.BooleanField()),
                ('overlay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overlay.collaborativeoverlay')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
