# Generated by Django 4.2.11 on 2024-04-20 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0010_collaborativeoverlay_allow_audio_youtubeembeditem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitchstreamembeditem',
            name='item_type',
            field=models.CharField(default='TwitchStreamEmbedItem', editable=False, max_length=32),
        ),
    ]
