# Generated by Django 4.2.11 on 2024-04-20 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0011_alter_twitchstreamembeditem_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitchstreamembeditem',
            name='volume',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='youtubeembeditem',
            name='volume',
            field=models.IntegerField(default=50),
        ),
    ]
