# Generated by Django 4.2.11 on 2024-04-27 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0013_counteritem_opacity_embeditem_opacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubeembeditem',
            name='start_time',
            field=models.IntegerField(default=0),
        ),
    ]
