# Generated by Django 4.2.11 on 2024-04-27 04:54

from django.db import migrations, models
import django.db.models.deletion
import overlay.models


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0014_youtubeembeditem_start_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twitchstreamembeditem',
            old_name='username',
            new_name='channel',
        ),
        migrations.CreateModel(
            name='TwitchVideoEmbedItem',
            fields=[
                ('id', models.CharField(default=overlay.models.id_gen, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(default='My Item', max_length=256)),
                ('x', models.IntegerField(default=-300)),
                ('y', models.IntegerField(default=-100)),
                ('z', models.IntegerField(default=50)),
                ('width', models.IntegerField(default=300)),
                ('height', models.IntegerField(default=100)),
                ('rotation', models.FloatField(default=0)),
                ('opacity', models.FloatField(default=1.0)),
                ('visible', models.BooleanField(default=True)),
                ('minimized', models.BooleanField(default=False)),
                ('item_type', models.CharField(default='TwitchVideoEmbedItem', editable=False, max_length=32)),
                ('video_id', models.CharField(blank=True, default='', max_length=256, verbose_name='Twitch Channel Name')),
                ('start_time', models.IntegerField(default=0)),
                ('paused', models.BooleanField()),
                ('muted', models.BooleanField()),
                ('volume', models.IntegerField(default=50)),
                ('overlay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overlay.collaborativeoverlay')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
