# Generated by Django 4.2.11 on 2024-07-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0017_alter_counteritem_crop_bottom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counteritem',
            name='crop_bottom',
            field=models.FloatField(default=0, verbose_name='Crop % (bottom)'),
        ),
        migrations.AlterField(
            model_name='counteritem',
            name='crop_left',
            field=models.FloatField(default=0, verbose_name='Crop % (left)'),
        ),
        migrations.AlterField(
            model_name='counteritem',
            name='crop_right',
            field=models.FloatField(default=0, verbose_name='Crop % (right)'),
        ),
        migrations.AlterField(
            model_name='counteritem',
            name='crop_top',
            field=models.FloatField(default=0, verbose_name='Crop % (top)'),
        ),
        migrations.AlterField(
            model_name='embeditem',
            name='crop_bottom',
            field=models.FloatField(default=0, verbose_name='Crop % (bottom)'),
        ),
        migrations.AlterField(
            model_name='embeditem',
            name='crop_left',
            field=models.FloatField(default=0, verbose_name='Crop % (left)'),
        ),
        migrations.AlterField(
            model_name='embeditem',
            name='crop_right',
            field=models.FloatField(default=0, verbose_name='Crop % (right)'),
        ),
        migrations.AlterField(
            model_name='embeditem',
            name='crop_top',
            field=models.FloatField(default=0, verbose_name='Crop % (top)'),
        ),
        migrations.AlterField(
            model_name='imageitem',
            name='crop_bottom',
            field=models.FloatField(default=0, verbose_name='Crop % (bottom)'),
        ),
        migrations.AlterField(
            model_name='imageitem',
            name='crop_left',
            field=models.FloatField(default=0, verbose_name='Crop % (left)'),
        ),
        migrations.AlterField(
            model_name='imageitem',
            name='crop_right',
            field=models.FloatField(default=0, verbose_name='Crop % (right)'),
        ),
        migrations.AlterField(
            model_name='imageitem',
            name='crop_top',
            field=models.FloatField(default=0, verbose_name='Crop % (top)'),
        ),
        migrations.AlterField(
            model_name='stopwatchitem',
            name='crop_bottom',
            field=models.FloatField(default=0, verbose_name='Crop % (bottom)'),
        ),
        migrations.AlterField(
            model_name='stopwatchitem',
            name='crop_left',
            field=models.FloatField(default=0, verbose_name='Crop % (left)'),
        ),
        migrations.AlterField(
            model_name='stopwatchitem',
            name='crop_right',
            field=models.FloatField(default=0, verbose_name='Crop % (right)'),
        ),
        migrations.AlterField(
            model_name='stopwatchitem',
            name='crop_top',
            field=models.FloatField(default=0, verbose_name='Crop % (top)'),
        ),
        migrations.AlterField(
            model_name='textitem',
            name='crop_bottom',
            field=models.FloatField(default=0, verbose_name='Crop % (bottom)'),
        ),
        migrations.AlterField(
            model_name='textitem',
            name='crop_left',
            field=models.FloatField(default=0, verbose_name='Crop % (left)'),
        ),
        migrations.AlterField(
            model_name='textitem',
            name='crop_right',
            field=models.FloatField(default=0, verbose_name='Crop % (right)'),
        ),
        migrations.AlterField(
            model_name='textitem',
            name='crop_top',
            field=models.FloatField(default=0, verbose_name='Crop % (top)'),
        ),
        migrations.AlterField(
            model_name='twitchstreamembeditem',
            name='crop_bottom',
            field=models.FloatField(default=0, verbose_name='Crop % (bottom)'),
        ),
        migrations.AlterField(
            model_name='twitchstreamembeditem',
            name='crop_left',
            field=models.FloatField(default=0, verbose_name='Crop % (left)'),
        ),
        migrations.AlterField(
            model_name='twitchstreamembeditem',
            name='crop_right',
            field=models.FloatField(default=0, verbose_name='Crop % (right)'),
        ),
        migrations.AlterField(
            model_name='twitchstreamembeditem',
            name='crop_top',
            field=models.FloatField(default=0, verbose_name='Crop % (top)'),
        ),
        migrations.AlterField(
            model_name='twitchvideoembeditem',
            name='crop_bottom',
            field=models.FloatField(default=0, verbose_name='Crop % (bottom)'),
        ),
        migrations.AlterField(
            model_name='twitchvideoembeditem',
            name='crop_left',
            field=models.FloatField(default=0, verbose_name='Crop % (left)'),
        ),
        migrations.AlterField(
            model_name='twitchvideoembeditem',
            name='crop_right',
            field=models.FloatField(default=0, verbose_name='Crop % (right)'),
        ),
        migrations.AlterField(
            model_name='twitchvideoembeditem',
            name='crop_top',
            field=models.FloatField(default=0, verbose_name='Crop % (top)'),
        ),
        migrations.AlterField(
            model_name='youtubeembeditem',
            name='crop_bottom',
            field=models.FloatField(default=0, verbose_name='Crop % (bottom)'),
        ),
        migrations.AlterField(
            model_name='youtubeembeditem',
            name='crop_left',
            field=models.FloatField(default=0, verbose_name='Crop % (left)'),
        ),
        migrations.AlterField(
            model_name='youtubeembeditem',
            name='crop_right',
            field=models.FloatField(default=0, verbose_name='Crop % (right)'),
        ),
        migrations.AlterField(
            model_name='youtubeembeditem',
            name='crop_top',
            field=models.FloatField(default=0, verbose_name='Crop % (top)'),
        ),
    ]
