# Generated by Django 4.2.11 on 2024-07-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0019_rename_visible_counteritem_visibility_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counteritem',
            name='visibility',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='embeditem',
            name='visibility',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='imageitem',
            name='visibility',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stopwatchitem',
            name='visibility',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='textitem',
            name='visibility',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='twitchstreamembeditem',
            name='visibility',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='twitchvideoembeditem',
            name='visibility',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='youtubeembeditem',
            name='visibility',
            field=models.IntegerField(default=0),
        ),
    ]
