# Generated by Django 4.2.11 on 2024-07-14 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0020_alter_counteritem_visibility_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counteritem',
            name='opacity',
            field=models.FloatField(default=100.0),
        ),
        migrations.AlterField(
            model_name='counteritem',
            name='visibility',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='embeditem',
            name='opacity',
            field=models.FloatField(default=100.0),
        ),
        migrations.AlterField(
            model_name='embeditem',
            name='visibility',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='imageitem',
            name='opacity',
            field=models.FloatField(default=100.0),
        ),
        migrations.AlterField(
            model_name='imageitem',
            name='visibility',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='stopwatchitem',
            name='opacity',
            field=models.FloatField(default=100.0),
        ),
        migrations.AlterField(
            model_name='stopwatchitem',
            name='visibility',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='textitem',
            name='opacity',
            field=models.FloatField(default=100.0),
        ),
        migrations.AlterField(
            model_name='textitem',
            name='visibility',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='twitchstreamembeditem',
            name='opacity',
            field=models.FloatField(default=100.0),
        ),
        migrations.AlterField(
            model_name='twitchstreamembeditem',
            name='visibility',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='twitchvideoembeditem',
            name='opacity',
            field=models.FloatField(default=100.0),
        ),
        migrations.AlterField(
            model_name='twitchvideoembeditem',
            name='visibility',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='youtubeembeditem',
            name='opacity',
            field=models.FloatField(default=100.0),
        ),
        migrations.AlterField(
            model_name='youtubeembeditem',
            name='visibility',
            field=models.IntegerField(default=1),
        ),
    ]
