# Generated by Django 4.2.11 on 2024-07-28 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0021_alter_counteritem_opacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counteritem',
            name='item_type',
        ),
        migrations.RemoveField(
            model_name='embeditem',
            name='item_type',
        ),
        migrations.RemoveField(
            model_name='imageitem',
            name='item_type',
        ),
        migrations.RemoveField(
            model_name='stopwatchitem',
            name='item_type',
        ),
        migrations.RemoveField(
            model_name='textitem',
            name='item_type',
        ),
        migrations.RemoveField(
            model_name='twitchstreamembeditem',
            name='item_type',
        ),
        migrations.RemoveField(
            model_name='twitchvideoembeditem',
            name='item_type',
        ),
        migrations.RemoveField(
            model_name='youtubeembeditem',
            name='item_type',
        ),
    ]
