# Generated by Django 4.2.11 on 2024-08-12 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0022_remove_counteritem_item_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='counteritem',
            name='drop_shadow_blur_radius',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='counteritem',
            name='drop_shadow_color',
            field=models.CharField(default='#000000', max_length=255),
        ),
        migrations.AddField(
            model_name='counteritem',
            name='drop_shadow_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='counteritem',
            name='drop_shadow_offset_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='counteritem',
            name='drop_shadow_offset_y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='counteritem',
            name='text_outline_color',
            field=models.CharField(default='#000000', max_length=255),
        ),
        migrations.AddField(
            model_name='counteritem',
            name='text_outline_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='counteritem',
            name='text_outline_width',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stopwatchitem',
            name='drop_shadow_blur_radius',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stopwatchitem',
            name='drop_shadow_color',
            field=models.CharField(default='#000000', max_length=255),
        ),
        migrations.AddField(
            model_name='stopwatchitem',
            name='drop_shadow_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stopwatchitem',
            name='drop_shadow_offset_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stopwatchitem',
            name='drop_shadow_offset_y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stopwatchitem',
            name='text_outline_color',
            field=models.CharField(default='#000000', max_length=255),
        ),
        migrations.AddField(
            model_name='stopwatchitem',
            name='text_outline_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stopwatchitem',
            name='text_outline_width',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='textitem',
            name='drop_shadow_blur_radius',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='textitem',
            name='drop_shadow_color',
            field=models.CharField(default='#000000', max_length=255),
        ),
        migrations.AddField(
            model_name='textitem',
            name='drop_shadow_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='textitem',
            name='drop_shadow_offset_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='textitem',
            name='drop_shadow_offset_y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='textitem',
            name='text_outline_color',
            field=models.CharField(default='#000000', max_length=255),
        ),
        migrations.AddField(
            model_name='textitem',
            name='text_outline_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='textitem',
            name='text_outline_width',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='counteritem',
            name='background',
            field=models.CharField(default='#000000', max_length=255),
        ),
        migrations.AlterField(
            model_name='counteritem',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=255),
        ),
        migrations.AlterField(
            model_name='counteritem',
            name='font',
            field=models.CharField(default='Roboto Mono', max_length=255),
        ),
        migrations.AlterField(
            model_name='stopwatchitem',
            name='background',
            field=models.CharField(default='#000000', max_length=255),
        ),
        migrations.AlterField(
            model_name='stopwatchitem',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=255),
        ),
        migrations.AlterField(
            model_name='stopwatchitem',
            name='font',
            field=models.CharField(default='Roboto Mono', max_length=255),
        ),
        migrations.AlterField(
            model_name='textitem',
            name='background',
            field=models.CharField(default='#000000', max_length=255),
        ),
        migrations.AlterField(
            model_name='textitem',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=255),
        ),
        migrations.AlterField(
            model_name='textitem',
            name='font',
            field=models.CharField(default='Roboto Mono', max_length=255),
        ),
    ]
