# Generated by Django 4.2.11 on 2024-08-12 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0023_counteritem_drop_shadow_blur_radius_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counteritem',
            old_name='background',
            new_name='background_color',
        ),
        migrations.RenameField(
            model_name='stopwatchitem',
            old_name='background',
            new_name='background_color',
        ),
        migrations.RenameField(
            model_name='textitem',
            old_name='background',
            new_name='background_color',
        ),
    ]
