# Generated by Django 4.2.11 on 2024-08-13 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0025_changelogentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='changelogentry',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
