# Generated by Django 4.2.11 on 2024-08-14 04:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0028_alter_changelogentry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelogentry',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 13, 23, 10, 27, 794068)),
        ),
    ]
