# Generated by Django 4.2.11 on 2024-09-12 02:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0029_alter_changelogentry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='counteritem',
            name='scroll_direction',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='counteritem',
            name='scroll_duration',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='embeditem',
            name='scroll_direction',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='embeditem',
            name='scroll_duration',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='imageitem',
            name='scroll_direction',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imageitem',
            name='scroll_duration',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='stopwatchitem',
            name='scroll_direction',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stopwatchitem',
            name='scroll_duration',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='textitem',
            name='scroll_direction',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='textitem',
            name='scroll_duration',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='twitchstreamembeditem',
            name='scroll_direction',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='twitchstreamembeditem',
            name='scroll_duration',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='twitchvideoembeditem',
            name='scroll_direction',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='twitchvideoembeditem',
            name='scroll_duration',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='youtubeembeditem',
            name='scroll_direction',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='youtubeembeditem',
            name='scroll_duration',
            field=models.FloatField(default=5.0),
        ),
        migrations.AlterField(
            model_name='changelogentry',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 11, 21, 26, 43, 523708)),
        ),
    ]
