# Generated by Django 5.1.1 on 2024-09-19 03:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0030_counteritem_scroll_direction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelogentry',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 18, 22, 22, 57, 351857)),
        ),
    ]
