# Generated by Django 5.1.1 on 2024-09-19 03:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0031_alter_changelogentry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='counteritem',
            name='view_lock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='embeditem',
            name='view_lock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imageitem',
            name='view_lock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stopwatchitem',
            name='view_lock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='textitem',
            name='view_lock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='twitchstreamembeditem',
            name='view_lock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='twitchvideoembeditem',
            name='view_lock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='youtubeembeditem',
            name='view_lock',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='changelogentry',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 18, 22, 30, 38, 667524)),
        ),
    ]
