# Generated by Django 5.1.1 on 2024-09-23 02:27

import datetime
import overlay.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0032_counteritem_view_lock_embeditem_view_lock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelogentry',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 22, 21, 27, 55, 323706)),
        ),
        migrations.AlterField(
            model_name='imageitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Max file size: 25MB', null=True, upload_to=overlay.models.media_directory_path, validators=[overlay.models.validate_file_size]),
        ),
    ]
