# Generated by Django 5.1.1 on 2024-09-23 03:27

import datetime
import django.db.models.deletion
import overlay.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0033_alter_changelogentry_date_alter_imageitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelogentry',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 22, 22, 27, 10, 434690)),
        ),
        migrations.CreateModel(
            name='AudioItem',
            fields=[
                ('id', models.CharField(default=overlay.models.id_gen, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(default='My Item', max_length=256)),
                ('x', models.IntegerField(default=-300)),
                ('y', models.IntegerField(default=-100)),
                ('z', models.IntegerField(default=50)),
                ('width', models.IntegerField(default=300)),
                ('height', models.IntegerField(default=100)),
                ('rotation', models.FloatField(default=0)),
                ('opacity', models.FloatField(default=100.0)),
                ('visibility', models.IntegerField(default=1)),
                ('minimized', models.BooleanField(default=False)),
                ('view_lock', models.BooleanField(default=False)),
                ('scroll_direction', models.IntegerField(default=0)),
                ('scroll_duration', models.FloatField(default=5.0)),
                ('crop_top', models.FloatField(default=0, verbose_name='Crop % (top)')),
                ('crop_left', models.FloatField(default=0, verbose_name='Crop % (left)')),
                ('crop_bottom', models.FloatField(default=0, verbose_name='Crop % (bottom)')),
                ('crop_right', models.FloatField(default=0, verbose_name='Crop % (right)')),
                ('audio', models.FileField(help_text='Max file size: 25MB', upload_to=overlay.models.media_directory_path, validators=[overlay.models.validate_file_size])),
                ('overlay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overlay.collaborativeoverlay')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
