# Generated by Django 5.1.1 on 2024-09-23 03:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0034_alter_changelogentry_date_audioitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelogentry',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 22, 22, 27, 42, 665244)),
        ),
    ]
