# Generated by Django 5.1.1 on 2024-09-23 03:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0035_alter_changelogentry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelogentry',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
