# Generated by Django 5.1.1 on 2024-09-23 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0036_alter_changelogentry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioitem',
            name='volume',
            field=models.FloatField(default=50.0),
        ),
    ]
