# Generated by Django 5.1.1 on 2024-10-30 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0038_audioitem_background_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvasitem',
            name='history',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
