# Generated by Django 5.1.1 on 2025-02-09 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0041_audioitem_position_lock_canvasitem_position_lock_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editor',
            old_name='twitch_id',
            new_name='identifier',
        ),
        migrations.AlterField(
            model_name='collaborativeoverlay',
            name='description',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
