# Generated by Django 5.1.1 on 2025-02-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0043_overlayuser_overlayuserid'),
    ]

    operations = [
        migrations.AddField(
            model_name='editor',
            name='id_type',
            field=models.IntegerField(default=0, verbose_name='Identification method'),
        ),
    ]
