# Generated by Django 5.1.1 on 2025-02-09 07:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0045_alter_editor_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='editor',
            unique_together={('owner', 'id_type', 'identifier')},
        ),
    ]
