# Generated by Django 5.1.1 on 2025-03-26 00:45

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0045_alter_editor_unique_together'),
    ]
    
    def set_action_value(apps, schema_editor):
      CanvasAction = apps.get_model("overlay", "CanvasAction")
      for canvasAction in CanvasAction.objects.all():
        actionStr = canvasAction.action_data.get("type", "none")
        if actionStr == "draw":
          canvasAction.action = 0
        elif actionStr == "erase":
          canvasAction.action = 1
        elif actionStr == "clear":
          canvasAction.action = 2
        else:
          canvasAction = -1
          
        canvasAction.save()

    operations = [
        migrations.RenameField(
            model_name='canvasaction',
            old_name='action',
            new_name='action_data',
        ),
        migrations.AddField(
            model_name='canvasaction',
            name='action',
            field=models.IntegerField(default=-1),
        ),
        migrations.RunPython(set_action_value),
    ]
