# Generated by Django 5.1.1 on 2025-06-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0049_twitchpollitem_twitchpredictionitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitchpollitem',
            name='bar_color',
            field=models.CharField(default='#EB5E28', max_length=255),
        ),
        migrations.AddField(
            model_name='twitchpollitem',
            name='title_color',
            field=models.CharField(default='#FFFFFF', max_length=255),
        ),
        migrations.AddField(
            model_name='twitchpredictionitem',
            name='bar_color',
            field=models.CharField(default='#EB5E28', max_length=255),
        ),
        migrations.AddField(
            model_name='twitchpredictionitem',
            name='title_color',
            field=models.CharField(default='#FFFFFF', max_length=255),
        ),
    ]
