# Generated by Django 5.2.1 on 2025-06-12 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0050_twitchpollitem_bar_color_twitchpollitem_title_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioitem',
            name='mirrored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='canvasitem',
            name='mirrored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='counteritem',
            name='mirrored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='embeditem',
            name='mirrored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imageitem',
            name='mirrored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stopwatchitem',
            name='mirrored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='textitem',
            name='mirrored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='twitchchatitem',
            name='mirrored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='twitchpollitem',
            name='mirrored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='twitchpredictionitem',
            name='mirrored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='twitchstreamembeditem',
            name='mirrored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='twitchvideoembeditem',
            name='mirrored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='youtubeembeditem',
            name='mirrored',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='audioitem',
            name='name',
            field=models.CharField(default='My Audio', max_length=256),
        ),
        migrations.AlterField(
            model_name='canvasitem',
            name='name',
            field=models.CharField(default='My Canvas', max_length=256),
        ),
        migrations.AlterField(
            model_name='counteritem',
            name='name',
            field=models.CharField(default='My Counter', max_length=256),
        ),
        migrations.AlterField(
            model_name='embeditem',
            name='name',
            field=models.CharField(default='My Embed', max_length=256),
        ),
        migrations.AlterField(
            model_name='imageitem',
            name='name',
            field=models.CharField(default='My Image', max_length=256),
        ),
        migrations.AlterField(
            model_name='stopwatchitem',
            name='name',
            field=models.CharField(default='My Stopwatch', max_length=256),
        ),
        migrations.AlterField(
            model_name='textitem',
            name='name',
            field=models.CharField(default='My Text', max_length=256),
        ),
        migrations.AlterField(
            model_name='twitchchatitem',
            name='name',
            field=models.CharField(default='My Twitch Chat', max_length=256),
        ),
        migrations.AlterField(
            model_name='twitchpollitem',
            name='name',
            field=models.CharField(default='My Twitch Poll', max_length=256),
        ),
        migrations.AlterField(
            model_name='twitchpredictionitem',
            name='name',
            field=models.CharField(default='My Twitch Prediction', max_length=256),
        ),
        migrations.AlterField(
            model_name='twitchstreamembeditem',
            name='name',
            field=models.CharField(default='My Twitch Stream', max_length=256),
        ),
        migrations.AlterField(
            model_name='twitchvideoembeditem',
            name='name',
            field=models.CharField(default='My Twitch Video', max_length=256),
        ),
        migrations.AlterField(
            model_name='youtubeembeditem',
            name='name',
            field=models.CharField(default='My YouTube Video', max_length=256),
        ),
    ]
