# Generated by Django 5.2.1 on 2025-06-13 18:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0051_audioitem_mirrored_canvasitem_mirrored_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OverlayUserId',
            new_name='OverlayUserInfo',
        ),
        migrations.RenameIndex(
            model_name='overlayuserinfo',
            new_name='overlay_ove_user_id_6fa4c6_idx',
            old_name='overlay_ove_user_id_0a32d0_idx',
        ),
    ]
