# Generated by Django 5.2.1 on 2025-06-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0052_rename_overlayuserid_overlayuserinfo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='overlayuserinfo',
            name='embed_stream',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='overlayuserinfo',
            name='notification_volume',
            field=models.FloatField(default=0.5),
        ),
    ]
