# Generated by Django 5.2.1 on 2025-06-14 21:01

import lusciousdev.util.modelutil
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0055_alter_countdownitem_timer_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countdownitem',
            name='timer_end',
            field=models.BigIntegerField(default=lusciousdev.util.modelutil.current_time_seconds),
        ),
    ]
