# Generated by Django 5.2.1 on 2025-06-30 04:40

import django.db.models.deletion
import lusciousdev.util.modelutil
import overlay.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0059_alter_audioitem_background_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatTrigger',
            fields=[
                ('id', models.CharField(default=lusciousdev.util.modelutil.id_gen, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(default='My Action', max_length=256)),
                ('cooldown', models.IntegerField(default=60)),
                ('action_data', models.JSONField(default=overlay.models.default_action_data)),
                ('trigger_phrase', models.CharField(max_length=500)),
                ('required_user_level', models.IntegerField(choices=[(0, 'Anyone'), (1, 'Subscriber'), (2, 'Vip'), (3, 'Moderator'), (4, 'Owner')], default=0)),
                ('occurances', models.IntegerField(default=1)),
                ('overlay', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='overlay.collaborativeoverlay')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
