# Generated by Django 5.2.1 on 2025-07-01 00:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0060_chattrigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='chattrigger',
            name='last_occurance',
            field=models.DateTimeField(default=datetime.datetime(1971, 1, 1, 0, 0, 1)),
        ),
    ]
