# Generated by Django 5.2.1 on 2025-07-01 00:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0061_chattrigger_last_occurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='chattrigger',
            name='occurance_window',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='chattrigger',
            name='last_occurance',
            field=models.DateTimeField(default=datetime.datetime(1971, 1, 1, 0, 0, 1, tzinfo=datetime.timezone.utc)),
        ),
    ]
