# Generated by Django 5.2.1 on 2025-07-01 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0062_chattrigger_occurance_window_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chattrigger',
            name='occurance_count',
            field=models.IntegerField(default=0),
        ),
    ]
