# Generated by Django 5.2.1 on 2025-07-01 00:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0063_chattrigger_occurance_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='chattrigger',
            name='last_trigger',
            field=models.DateTimeField(default=datetime.datetime(1971, 1, 1, 0, 0, 1, tzinfo=datetime.timezone.utc)),
        ),
    ]
