# Generated by Django 5.1.1 on 2025-08-10 02:58

import datetime
import django.db.models.deletion
import lusciousdev.util.modelutil
import overlay.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0064_chattrigger_last_trigger'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorseGameItem',
            fields=[
                ('id', models.CharField(default=lusciousdev.util.modelutil.id_gen, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('x', models.IntegerField(default=-300)),
                ('y', models.IntegerField(default=-100)),
                ('z', models.IntegerField(default=50)),
                ('width', models.IntegerField(default=300)),
                ('height', models.IntegerField(default=100)),
                ('rotation', models.FloatField(default=0)),
                ('mirrored', models.BooleanField(default=False)),
                ('background_enabled', models.BooleanField(default=False)),
                ('background_color', models.CharField(default='#000000FF', max_length=255)),
                ('opacity', models.FloatField(default=100.0)),
                ('visibility', models.IntegerField(default=1)),
                ('minimized', models.BooleanField(default=False)),
                ('view_lock', models.BooleanField(default=False)),
                ('position_lock', models.BooleanField(default=False)),
                ('scroll_direction', models.IntegerField(default=0)),
                ('scroll_duration', models.FloatField(default=5.0)),
                ('crop_top', models.FloatField(default=0, verbose_name='Crop % (top)')),
                ('crop_left', models.FloatField(default=0, verbose_name='Crop % (left)')),
                ('crop_bottom', models.FloatField(default=0, verbose_name='Crop % (bottom)')),
                ('crop_right', models.FloatField(default=0, verbose_name='Crop % (right)')),
                ('name', models.CharField(default='My Horse Game', max_length=256)),
                ('seed', models.IntegerField(default=overlay.models.generate_seed)),
                ('racers', models.IntegerField(default=4)),
                ('overlay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overlay.collaborativeoverlay')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StreamEndTrigger',
            fields=[
                ('id', models.CharField(default=lusciousdev.util.modelutil.id_gen, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(default='My Action', max_length=256)),
                ('cooldown', models.IntegerField(default=60)),
                ('last_trigger', models.DateTimeField(default=datetime.datetime(1971, 1, 1, 0, 0, 1, tzinfo=datetime.timezone.utc))),
                ('action_data', models.JSONField(default=overlay.models.default_action_data)),
                ('overlay', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='overlay.collaborativeoverlay')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StreamStartTrigger',
            fields=[
                ('id', models.CharField(default=lusciousdev.util.modelutil.id_gen, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(default='My Action', max_length=256)),
                ('cooldown', models.IntegerField(default=60)),
                ('last_trigger', models.DateTimeField(default=datetime.datetime(1971, 1, 1, 0, 0, 1, tzinfo=datetime.timezone.utc))),
                ('action_data', models.JSONField(default=overlay.models.default_action_data)),
                ('overlay', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='overlay.collaborativeoverlay')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
