# Generated by Django 5.2.5 on 2025-08-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0066_horsegameitem_prediction_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='horsegameitem',
            name='gallop_volume',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='horsegameitem',
            name='volume',
            field=models.FloatField(default=100.0),
        ),
    ]
