# Generated by Django 5.2.5 on 2025-12-30 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0067_horsegameitem_gallop_volume_horsegameitem_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='horsegameitem',
            name='time_limit',
            field=models.IntegerField(default=120),
        ),
    ]
