# Generated by Django 5.1.1 on 2025-01-28 19:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistInfo',
            fields=[
                ('playlist_id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('last_fetched', models.DateTimeField(default=django.utils.timezone.now)),
                ('info', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
